---
language: ruby
before_install: "gem install bundler"
bundler_args: --without tools
script: bundle exec rspec
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
  - jruby-9.2.6.0
  - jruby-head
gemfile:
  - gemfiles/rails51.gemfile
  - gemfiles/rails60.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.2.6.0
  fast_finish: true
branches:
  only: master
