rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - jruby-18mode
  - jruby-19mode
gemfile:
  - gemfiles/rails23.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
