rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
gemfile:
  - gemfiles/rails23.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails32_pg.gemfile
  - gemfiles/rails32_mysql.gemfile
  - gemfiles/rails40.gemfile
install:
  - ./rebund/run download
  - bundle install --path ../vendor/bundle
after_script:
  - ./rebund/run upload
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails23.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/rails40.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails40.gemfile
before_script:
  - psql -c 'create database fuzzily_test;' -U postgres
  - mysql -e 'create database fuzzily_test;'
env:
  global:
    - TRAVIS=TRUE
    - secure: bXHSygHAYQtuVj+rZSaXOQJFWVQEwnOm3HOivKfh+0CADtHJ3TxWSPHpwWPDx/+GDqad4eU/9qfhb5GBr1lJMRJmSi5iJ53KOZxilHqL0fo070mSsLEvOSnT6fKwIe30+3LTYVR6oKEwdyt9EI/yP5aGO4klncZkvI2zqAoy6YI=
